### ISSUE TITLE
Node 6 Compile issues

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [webpack/webpack-dev-middleware#90]
After updating to Node 6 I am now getting the following issues:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x641b9ec9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x31a5c5dec944] (this=0x766c05fe979 <an Object with map 0x34b7d5a90559>#1#,module=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    2: load [module.js:~447] [pc=0x31a5c587cc36] (this=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x31a5c543899d] (this=0x641b9e04189 <undefined>,module=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x31a5c530961b
 8: 0x31a5c5dec944
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x641b9ec9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x31a5c5dec944] (this=0x766c05fe979 <an Object with map 0x34b7d5a90559>#1#,module=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    2: load [module.js:~447] [pc=0x31a5c587cc36] (this=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x31a5c543899d] (this=0x641b9e04189 <undefined>,module=0x12cc82d850e1 <a Module with map 0x34b7d5a181b9>#2#,filename=0x12cc82d850a9 <String[118]: /Users/tal.woolf/developer/frontend/docker-test/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x31a5c530961b
 8: 0x31a5c5dec944
```

**Comment by shinzui** [comment]
Deleting your node_modules directory and reinstalling your packages should fix this.

**Comment by jvilk** [comment]
@shinzui that solution does not appear to work for me. I deleted `node_modules`, ran `npm cache clean`, and still receive the following output:

```
webpack-dev-server on port 8080
 10% 0/1 build modulests-loader: Using typescript@1.8.10 and /Users/jvilk/Code/doppio-demo/tsconfig.json
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x3610418c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x30a0f823a2c4] (this=0x12dbb0fea111 <an Object with map 0x15a418242f81>#1#,module=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    2: load [/Users/jvilk/Code/doppio-demo/node_modules/coffee-script/lib/coffee-script/register.js:45] [pc=0x30a0f72bc054] (this=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x30a0f723899d] (this=0x361041804189 <undefined>,module=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    4: _load [module.js:407] [pc=0x30a0f72 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x30a0f710961b
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.

==== JS stack trace =========================================

Security context: 0x3610418c9fa9 <JS Object>#0#
    1: .node [module.js:568] [pc=0x30a0f823a2c4] (this=0x12dbb0fea111 <an Object with map 0x15a418242f81>#1#,module=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    2: load [/Users/jvilk/Code/doppio-demo/node_modules/coffee-script/lib/coffee-script/register.js:45] [pc=0x30a0f72bc054] (this=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x30a0f723899d] (this=0x361041804189 <undefined>,module=0x34877f3b9699 <a Module with map 0x15a4182181b9>#2#,filename=0x34877f3b9671 <String[74]: /Users/jvilk/Code/doppio-demo/node_modules/fsevents/build/Release/fse.node>)
    4: _load [module.js:407] [pc=0x30a0f72 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 7: 0x30a0f710961b
Version: webpack 1.13.1
 Asset     Size  Chunks             Chunk Names
app.js  1.05 MB       0  [emitted]  main
```

I'm guessing something is relying on an out-of-date `fsevents`?

**Comment by shinzui** [comment]
@jvilk Sorry, I just tried to verify again and I am getting the same warnings. I don't remember what I did last time to remove them, but I've since reverted back to node 5 since I was having problems with another package.

**Comment by etcook** [comment]
Running 6.2.2 and seeing this.

**Comment by christian-schulze** [comment]
Was having very similar issue with node 6.2.2, did the following to fix:
```
npm upgrade fsevents --save
npm upgrade node-sass --save
```

versions in package.json should be:
```javascript
"fsevents": "^1.0.12",
"node-sass": "^3.8.0"
```

**Comment by SpaceK33z** [comment]
It has something to do with your cache. This package works fine on Node v6.

**Comment by JoshLipps** [comment]
An old version of node-sass seems to have been causing this for me. Thanks @christian-schulze
